### ISSUE TITLE
Thanks for this!

### ISSUE THREAD

**Issue by jvcleave** [ascent12/drm_doc#2]
Would really love to see the atomic stuff. I am trying to get my head around this working on some stuff on the RPI4 and this has been helpful.

**Comment by ascent12** [comment]
You're welcome. I did eventually want to continue with something more complete, but https://gitlab.freedesktop.org/daniels/kms-quads became a pretty good example to point people at for atomic specifically.

**Comment by jvcleave** [comment]
I did find that one and with a few tweaks (disabling VT) it does work on the RPI4 so will be digging into that :)
